spring.application.name=bloco-notas

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/bloco_notas}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}
jwt.secret=${JWT_SECRET}